import Header from "@/partials/Header";
import { Container } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

export const metadata = {
    title: "Digestify",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main>
                    <Container>
                        {children}
                    </Container>
                </main>
            </body>
        </html>
    );
}
